import * as React from "react"
import '../../styles/blogposts.css'
import Layout from "../../components/layout"
import Seo from "../../components/seo"

let blogdata={
  link:"/blogs/gravit_waves",
  title:"GRAVITATIONAL WAVES: THE SHERLOCK HOLMES OF COSMIC MYSTERIES",
  author:'',
  autohorpos:'',
  authorimg:"",
  description:`Occasionally at night, looking at skies so beautifully cladded with shimmering stars, we have always wondered what goes in and out of our eyesight.`,
  image:"https://ik.imagekit.io/iam6kb9qx/gravitationalwaves.jpg?updatedAt=1703738487111",
  content : [
    <div className="blogbody">
        <h2 className="MainHeading">Aditya L1: India's Quest to Touch the Sun</h2>

   
        <h3 className="SubHeading">Introduction:</h3>
        <p>
        Occasionally at night, looking at skies so beautifully cladded with shimmering stars, we have always wondered what goes in and out of our eyesight. 
        Those silent whispers, secrets so untold, and those conversations the cosmos hold have always perked up our ears in curiosity, tempting us to be a part of the universe’s 
        darkest secrets and to know more about those exquisite particles hiding in there never showing itself to mankind.
        Gravitational waves- a phenomenon ever so powerful with the capability to reveal profound insights into the nature of spacetime, presented itself as the solution. 

        </p>
        <h3 className="SubHeading">Finding the notes: Discovery</h3>
        <p>Portrayed in earlier times as the gravitational equivalent of electromagnetic waves, it was Albert Einstein who predicted ‘Gravitational Waves’ in their finality in his general theory of relativity which wove together the extreme concepts of space and time. 
         Due to the continuous dissipation in energy that it undergoes, even Einstein believed it would never be detected, but all those disrupting thoughts changed on the fortunate morning of September 14, 2015,
          when LIGO (Laser Interferometer Gravitational-Wave Observatory) detected gravitational waves for the first time. 
          It was generated by the collision of two black holes about 1.3 billion light years away, thus validating Einstein’s predictions and paving a new era for astrophysics. </p>
          <br></br>
        <figure>
            <img src="https://ik.imagekit.io/iam6kb9qx/Ligo%20livingston%20interferometer.jpg?updatedAt=1703737618771" alt="LIGO Livingston Interferometer." class="blogImage" />
           <figcaption> LIGO Livingston Interferometer.</figcaption>
        </figure>
        <br></br>

        <h3 className="SubHeading">The Cosmic Magic: Unveiling</h3>
        <p> 
        Deemed as minuscule ripples in the fabric of spacetime, gravitational waves which can be detected are caused by some of the most violent and energetic processes in the universe such as the collision of rapidly rotating lumpy neutron stars or black holes orbiting around each other. 
        Travelling at the speed of light, these waves encode much-regarded information about their celestial origins and help in determining the nature of gravity on the same. 
        The frequency of the wave correlates directly with the masses of the object while its strength is a clear indicator of the distance of the object from the place detected.
        By thoroughly analyzing the data even additional system characteristics such as mass spin and orbit eccentricity can also be detected.
 
        </p>
        <br></br>
        <figure>
            <img src="https://ik.imagekit.io/iam6kb9qx/spacetime.jpg?updatedAt=1703737618723" alt="Bending of space" class="blogImage" />
           <figcaption></figcaption>
        </figure>
        <br></br>
        <p>
        Historically, scientists exclusively relied on electromagnetic waves for spatial discoveries which provided them with a different but complimentary view of the universe.
        Gravitational waves, however, are fundamentally unrelated to EM radiation and that is what makes it much more compatible than traditional astronomy.
        As we know, electromagnetic radiations are emitted from objects that produce light, but in the cosmic realm of unending darkness, some particles do not produce the same, yet are to be discovered. 
        Thus, making gravitational waves an essential tool in spacetime discoveries.
        </p>

        <h3 className="SubHeading">The Curtains: Conclusion</h3>
        <p> 

        Gravitational waves, once theoretical, are now concrete evidence of a cosmic phenomenon waiting to be unraveled. 
        This journey into spacetime ripples is not just a mere scientific triumph but a deep exploration of the interconnected complexities within, which could pave the way for our ongoing quest to put together the very heart of our vast universe.
        </p>


        
        <div className="sources">
            <h3 className="MiniSubHeading">Read more</h3>
              <ul>
              <li><a href="link"> source</a></li>
              </ul>  
        </div>
        <p className="ClosingQoutes" >
            We hope this blog post has sparked your curiosity, just as the nodes on the screen come alive when touched. Stay
            tuned for more exciting content next week!
        </p>
        </div>
        ,
  ],

}

const EventPage = () => {
  return (
    <Layout route={blogdata.link}>
    <Seo
      title={blogdata.title}
      image={blogdata.image}
    />
    <div className="pt-5 pb-10 px-2 sm:px-10">
      <div className="rounded-lg shadow-2xl glass-effect">
     <div id="blogbox">
     <div className="postheading"><h1>{blogdata.title}</h1></div>
        <div className="postdescriptiont"> 
           <p>{blogdata.description}</p> 
           <div className="authordata">
                 <img className="authorimage" src={blogdata.authorimg} alt={blogdata.author} />
                 {blogdata.author}<br></br>
                 {blogdata.autohorpos}
           </div>
        </div>
        <img className="postimage" src={blogdata.image} alt={blogdata.title} />
        <div className="postcontent">{blogdata.content}</div>
     </div>
      </div>
    </div>
  </Layout>
  )
}

export default EventPage
