name: Build

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Cache build
        id: node_build-cache
        uses: actions/cache@v2
        with:
          path: public
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Gatsby Build
        run: npm run build
